id: 640ddf7a191740a3baaa98e61ecc6e4e
title: Toh_99-The_Blessed_One%27s_Wisdom_That_Leads_to_Infinite_Certainty-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-047-001
  eft-text-version: 1.26.3 2020
